### ISSUE TITLE
Links in the app (EUA) don't work

### ISSUE THREAD

**Issue by Son-of-Cronus** [tomdoyle87/osmc-linux-installer#3]
Works great but..
I did find the link to the End User Agreement doesn't work, cause it want's to open Firefox as root. 
That's not good!
Not sure why Firefox, since Brave is my preferred/standard browser, but i do have Firefox installed.
The Buttons to share on Twitter and Facebook didn't work as well, probably the same reason.
(forgot to look in the terminal as to why, sorry)

But there are non that prevent you from using it.

**Comment by tomdoyle87** [comment]
Hi, 

***DISCLAIMER The osmc installer for Windows, Mac & Linux is due a rewrite. Keeping the the current installers working are a best effort, but not everything will work as expected.***

In order to write to the USB/SD card, the installer is launched as root. I'll take a look at the relevant code and attempt to step down the user for this bit.  As for the browser I suspect this is set by system wide variable $BROWSER,  so opening in a browser other than firefox, may not be easy.  

No promises I will be able to get this to work, but in the mean time; You can right-click the link and copy and paste in to a browser window. 

Regards Tom.

**Comment by tomdoyle87** [comment]
Hi, 

This isn't fixable without a complete re-write. Which is due, but out of my skill set. 

The best I can do is add an instruction to right click and copy to view EULA. @samnazarko any thoughts?

Regards Tom.

**Comment by Son-of-Cronus** [comment]
@tomdoyle87 
you already did awesome work, these bugs are in my opinion not stopping anybody from using the app.
(maybe a way around: you could just include the EULA text and open it in a popup like screen)

Used it 4 times now, never have had any trouble! 

I just tested them links cause it seems logical to do so, to me, as i was testing your hard work anyway.
And i seem to have a eh "talent" to find bugs, so much i have been nicknamed IvyTest elsewhere...
Glad i could help a bit with testing, and thank you again for making this happening.

**Comment by tomdoyle87** [comment]
"(maybe a way around: you could just include the EULA text and open it in a popup like screen)"

I prefer this over my suggestion. I'll give this ago 

Thanks Tom.

**Comment by samnazarko** [comment]
There’s no EULA per say, it’s just the GPL. As we prompt it on first boot anyway this isn’t really an issue

On 21 May 2022, at 19:10, tomdoyle87 ***@***.***> wrote:

﻿

"(maybe a way around: you could just include the EULA text and open it in a popup like screen)"

I prefer this over my suggestion. I'll give this ago

Thanks Tom.

**Comment by tomdoyle87** [comment]
So I've checked the Windows Installer and the be behaviour is the same (right click, copy and paste in browser). The Aim is to keep in-line with upstream, so unless this changes on Windows & Mac installer; will leave as is.
